RSA SigVer Capability Registration & Multiple RSA Cap Modes Registration
melinovi/libacvp pull request #1
Opened 2017-08-03 17:13 UTC by nayrpg

Added capability registration for RSA SigVer, along with support for registering multiple signature type capabilities for both SigVer and SigGen. *Multiple KeyGen capability registration was not added*

2017-08-03 18:32 UTC, bfussell requested changes
I would omit the acvp_app binary from the changeset.
Otherwise looks good !

2017-08-07 14:01 UTC, nayrpg commented
On the acvp_app binary should I just ignore it on my commit or do we want to add it to the git ignore file? @bfussell

2017-08-07 14:08 UTC, bfussell commented
Just ignore it on the commit

2017-08-07 14:08 UTC, bfussell approved these changes

2017-08-07 16:15 UTC, nayrpg commented
Making a new pull request with the suggestions that Norm and Barry asked for.

2017-08-07 16:15 UTC, closed without merging

2017-08-07 18:57 UTC, ashman-p commented on app/app_main.c
> +//	  rv = acvp_enable_rsa_cap_sig_type_parm(ctx, ACVP_RSA, ACVP_RSA_MODE_SIGVER, RSA_SIG_TYPE_X931, MOD_RSA_2048, ACVP_RSA_SHA_512);
A general comment ... you may want to remove the commented lines of code.